matrix:
  include:
  - language: python
    python: 2.7
    install:
    - pip install -r python/requirements.txt
  - language: node_js
    node_js:
    - "node"
    before_install:
    - npm install npm@latest -g
    script:
    - npm run build