matrix:
  include:
  - language: python
    python: 2.7
    install:
    - pip install -r python/requirements.txt
    script:
    - echo "no tests yet"
  - language: node_js
    node_js:
    - "10"
    script:
    - npm run build