#!/usr/bin/env python

import json
import sys
import os
import numpy as np
import cherrypy
from cherrypy.lib.static import serve_file
from explorer import Model

STATIC_DIR = os.path.dirname(os.path.realpath(__file__)) + '/../build'
CACHE = {}

class ApiController(object):

    @cherrypy.expose
    @cherrypy.tools.json_out()
    def explore(self,
                query=None,
                limit='1000',
                enable_clustering='',
                num_clusters='30'):
        cache_key = '-'.join([query, limit, enable_clustering, num_clusters])
        result = CACHE.get(cache_key, {})
        if len(result) > 0:
            return {'result': CACHE[cache_key], 'cached': True}
        try:
            exploration = self.model.explore(query, limit=int(limit))
            exploration.reduce()
            if len(enable_clustering):
                if (len(num_clusters)):
                    num_clusters = int(num_clusters)
                exploration.cluster(num_clusters=num_clusters)
            result = exploration.serialize()
            CACHE[cache_key] = result
            return {'result': result, 'cached': False}
        except KeyError:
            return {'error': {'message': 'No vector found for ' + query}}

    def numpy_json_handler(*args, **kwargs):
        value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
        return json.dumps(value, cls=NumpyEncoder)

    @cherrypy.expose
    @cherrypy.tools.json_out(handler=numpy_json_handler)
    def compare(self, **kw):
        limit = kw.pop('limit', '100')
        queries = kw.pop('queries', [])
        try:
            result = self.model.compare(queries, limit=int(limit))
            return {'result': result}
        except KeyError:
            return {'error': {'message': 'No vector found for {}'.format(queries)}}

    @cherrypy.expose
    @cherrypy.tools.json_out()
    def autocomplete(self, query=None, limit='20'):
        result = self.model.autocomplete(query, limit=int(limit))
        return {'result': result}

class NumpyEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, (np.int_, np.intc, np.intp, np.int8,
                            np.int16, np.int32, np.int64, np.uint8,
                            np.uint16, np.uint32, np.uint64)):
            return int(obj)
        elif isinstance(obj, (np.float_, np.float16, np.float32,
                              np.float64)):
            return float(obj)
        elif isinstance(obj,(np.ndarray,)): #### This is the fix
            return obj.tolist()
        return json.JSONEncoder.default(self, obj)

class AppController(object):

    @cherrypy.expose
    def index(self, **kw):
        return serve_file(STATIC_DIR + '/index.html', "text/html")

if __name__ == '__main__':
    if len(sys.argv) < 2:
        sys.stderr.write('Usage: {} <Word2Vec model file>\n'.format(sys.argv[0]))
        sys.exit()
    api_controller = ApiController()
    api_controller.model = Model(sys.argv[1])
    app_controller = AppController()
    dispatch = cherrypy.dispatch.RoutesDispatcher()
    dispatch.connect('api', '/api/:action', controller=api_controller)
    dispatch.connect('app', '/:id', controller=app_controller, action="index")
    dispatch.connect('app', '/', controller=app_controller, action="index")
    app = cherrypy.tree.mount(None, config={
            '/': {
                'request.dispatch': dispatch,
                'tools.staticdir.on': True,
                'tools.staticdir.dir': STATIC_DIR
            }
        })
    cherrypy.config.update( {'server.socket_host': '0.0.0.0'} )
    cherrypy.engine.start()
    cherrypy.engine.block()
